# Generated by Django 5.0.2 on 2024-03-02 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Refresco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('sabor', models.CharField(max_length=20)),
                ('marca', models.CharField(max_length=20)),
                ('presentacion', models.CharField(choices=[('botella', 'botella'), ('lata', 'lata'), ('botella mini', 'botella mini')], max_length=20)),
                ('fecha_creado', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
